version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/simple-musician-app

hooks:
  BeforeInstall:
    - location: stop_container.sh
      timeout: 30
      runas: ec2-user

  AfterInstall:
    - location: start_container.sh
      timeout: 60
      runas: ec2-user
